version: "3.8"

services:
  app:
    build:
      context: .
    command: bash start.sh
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      GRADLE_USER_HOME: /box
    volumes:
      - .:/flashcards-dio
      - box:/box
    depends_on:
      - db
  db:
    image: mongo:5.0.9
    environment:
      MONGO_INITDB_ROOT_USERNAME: flashcards-dio
      MONGO_INITDB_ROOT_PASSWORD: flashcards-dio
      MONGO_INITDB_DATABASE: flashcards-dio
    ports:
      - "27017:27017"
  box:
    image: busybox
    volumes:
      - /box
volumes:
  db:
  box: